Document: libcrypt1
Title: Debian libcrypt1 Manual
Author: <insert document author here>
Abstract: This manual describes what libcrypt1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libcrypt1/libcrypt1.sgml.gz

Format: postscript
Files: /usr/share/doc/libcrypt1/libcrypt1.ps.gz

Format: text
Files: /usr/share/doc/libcrypt1/libcrypt1.text.gz

Format: HTML
Index: /usr/share/doc/libcrypt1/html/index.html
Files: /usr/share/doc/libcrypt1/html/*.html
